version: '3'

services:
  server:
    image: nginx:1.17.2
    volumes:
      - ./configs/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./apps/verification/dist/index.js:/var/www/parabola/js/verification.js
    depends_on:
      - core
    ports:
      - 8080:80
      - 443:443

  core:
    image: crystallang/crystal
    command: crystal src/main.cr
    hostname: core
    working_dir: /app
    volumes:
      - ./apps/core:/app

  verification:
    image: node:12.8.1
    hostname: verification
    working_dir: /app
    volumes:
      - ./apps/verification:/app
